apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: testeck
spec:
  version: 7.10.0
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master-nodes
    count: 1
    config:
      node.store.allow_mmap: false
      node.roles: ["master"]
    # volumeClaimTemplates:
    # - metadata:
    #     name: elasticsearch-data
    #   spec:
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 1Gi
    #     storageClassName: hostpath
  - name: data-nodes
    count: 1
    config:
      node.store.allow_mmap: false
      node.roles: ["data", "ingest"]
    # volumeClaimTemplates:
    # - metadata:
    #     name: elasticsearch-data
    #   spec:
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 2Gi
    #     storageClassName: hostpath